name: Zip Xcode
run-name: Zip up Xcode in a tarball
on: [push]
jobs:
  Tarball:
    runs-on: macos-14
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
#      - name: Swap Xcode version
#        uses: maxim-lobanov/setup-xcode@v1
#        with:
#          xcode-version: latest
#      - name: Create working directories
#        run: mkdir $GITHUB_WORKSPACE/workroot
#      - name: Get information on runner
#        run: python3 $GITHUB_WORKSPACE/get_runner_info.py $GITHUB_WORKSPACE/workroot/system_log.txt
#      - name: Tarball Xcode install
#        run: python3 $GITHUB_WORKSPACE/tarball_xcode.py $GITHUB_WORKSPACE
      - name: Download artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ship_folder
          path: /Applications/Xcode_15.2.app
